### ISSUE TITLE
add forty8fiftylabs.com to openshift commons

### ISSUE THREAD

**Issue by dmueller2001** [openshift-cs/commons.openshift.org#639] opened 2018-05-04 10:32 UTC
url: forty8fiftylabs.com
logo: http://www.forty8fiftylabs.com/wp-content/uploads/2017/09/F8F-3C-logo-Final-HORZ-with-Tag.png

@wgordon17 @jiri-fiala

**Comment by jiri-fiala** [comment] 2018-05-04 12:42
This seems to be a duplicate of #632

**Closed by jiri-fiala** 2018-05-04 12:42 UTC
Labels: duplicate
